### ISSUE TITLE
Add brief instructor note to 01-Intro and Appendix z about how far to get on "Day 1"...

### ISSUE THREAD

**Issue by SteveDelFante** [chef-training/chef-fundamentals-4.x#69]
For in-person class. Perhaps say you should get to 08-workstation-installation or even as far as 09-chef-server module by the end of Day 1. Should we do the same for VILT (online) scenario?

**Comment by burtlo** [comment]
In the introduction Section it is displayed in a slide.

<img width="729" alt="screen shot 2015-10-05 at 12 08 48 pm" src="https://cloud.githubusercontent.com/assets/244426/10287633/dd873aaa-6b59-11e5-9047-7dca41d848d5.png">

**Comment by burtlo** [comment]
For teaching online we need to create a new slide because we currently teach it across three days:

### Day 1

* Getting a Workstation
* Using Resources
* Building Cookbooks
* Testing with Test Kitchen
* Local Workstation Installation

### Day 2

* Testing with Test Kitchen
* Details about the System
* Desired State and Data
* Connecting to Chef Server

### Day 3

* Community Cookbooks
* Managing Multiple Notes
* Roles
* Search
* Environments
